---

- name: login via oc cli tool
  shell:
    cmd: oc login {{ oc_url }} -u {{ oc_user }} -p {{ oc_pass }}

- name: render and apply all templates for argocd
  loop: "{{ argo_manifests }}"
  loop_control:
    label: "{{ item.name }}"
  include_tasks: "_apply_manifest_chunk.yaml"
