apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: logging-appset
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - name: cluster-1
            server: https://kubernetes.default.svc
            branch: main
  syncPolicy: {}
  template:
    metadata:
      name: "{{ .name }}-logging-app"
    spec:
      project: default
      source:
        repoURL: git@github.com:florian-waldecker/openshift-bootcamp.git
        targetRevision: "{{ .branch }}"
        path: argocd/manifests/logging/overlays/{{ .name }}
      destination:
        server: "{{ .server }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
